name: dask-distributed
channels:
  - conda-forge
dependencies:
  - python=3.10
  - click=8.0
  - cloudpickle=3.0.0
  - cytoolz=0.11.2
  - jinja2=2.10.3
  - locket=1.0.0
  - msgpack-python=1.0.2
  - packaging=20.0
  - pyparsing<3.3  # Newer versions of pyparsing break with old versions of packaging
  - setuptools < 71  # Newer versions of setuptools break with packaging<24
                     # https://github.com/pypa/setuptools/issues/4496
  - psutil=5.8.0
  - pyyaml=5.4.1
  - sortedcontainers=2.0.5
  - tblib=1.6.0
  - toolz=0.12.0
  - tornado=6.2.0
  - urllib3=1.26.5
  - zict=3.0.0
  # Distributed depends on the latest version of Dask
  - pip
  - pip:
    - git+https://github.com/dask/dask
  # test dependencies
  - pytest<8.4  # Pin due to https://github.com/pytest-dev/pytest-cov/issues/693
  - pytest-cov
  - pytest-faulthandler
  - pytest-repeat
  - pytest-rerunfailures
  - pytest-timeout
