name: dask-distributed
channels:
  - conda-forge
  - defaults
dependencies:
  # required dependencies
  - python=3.9
  - click=8.0
  - cloudpickle=1.5.0
  - cytoolz=0.10.1
  - jinja2=2.10.3
  - locket=1.0.0
  - msgpack-python=1.0.0
  - packaging=20.0
  - psutil=5.7.2
  - pyyaml=5.3.1
  - sortedcontainers=2.0.5
  - tblib=1.6.0
  - toolz=0.10.0
  - tornado=6.0.4
  - urllib3=1.24.3
  - zict=2.2.0
  # Distributed depends on the latest version of Dask
  - partd=1.2.0
  - pip
  - pip:
    - git+https://github.com/dask/dask
  # optional dependencies used by distributed
  - asyncssh=1.18.0
  - bokeh=2.4.2
  - conda=4.8.5
  - crick=0.0.3
  - cryptography
  - fsspec=2021.09.0
  - gilknocker=0.4.0
  - ipykernel=5.3.4
  - IPython=7.16.1
  - ipywidgets=7.5.0
  - jupyter_server=1.0.4
  - jupyter-server-proxy=1.0
  - lz4=4.3.2
  - netcdf4=1.5.4
  - numpy=1.21
  - pandas=1.3
  - paramiko=2.7.1
  - prometheus_client=0.3.0
  - pyarrow=7.0
  - pynvml=8.0.1
  - python-snappy=0.5.4
  - setproctitle=1.1.10
  # - stacktrace  # still imported in places but not available for python>3.7 
  - traitlets=4.3.3
  - typing_extensions=3.10.0
  - zstandard=0.14.0  # TODO: bump min version in other files, remove compat code
  # test dependencies
  - pytest
  - pytest-cov
  - pytest-faulthandler
  - pytest-repeat
  - pytest-rerunfailures
  - pytest-timeout
