name: dask-distributed
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - click=6.7
  - cloudpickle=1.5.0
  - jinja2
  - msgpack-python=0.6.0
  - openssl<3 # TODO: Add note about why this is needed
  - psutil=5.4.7
  - sortedcontainers=2.0.4
  - tblib=1.6.0
  - toolz=0.10.0
  - tornado=5
  - zict=0.1.3
  - pyyaml
  - setuptools
  # test dependencies
  - pytest
  - pytest-asyncio<0.14.0
  - pytest-faulthandler
  - pytest-repeat
  - pytest-rerunfailures
  - pytest-timeout
  - pip
  - pip:
    # Distributed depends on the latest version of Dask
    - git+https://github.com/dask/dask