name: dask-distributed
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - packaging
  - pip
  - asyncssh
  - bokeh
  - click
  - cloudpickle
  - coverage
  - cython  # Only tested here; also a dependency of crick
  - dask  # overridden by git tip below
  - filesystem-spec
  - gilknocker>=0.4.0
  - h5py
  - ipykernel <6.22.0  # https://github.com/dask/distributed/issues/7688
  - ipywidgets <8.0.5  # https://github.com/dask/distributed/issues/7688
  - jinja2 >=2.10.3
  - locket >=1.0
  - lz4 >=0.23.1  # Only tested here
  - msgpack-python
  - netcdf4
  - paramiko
  - pre-commit
  - prometheus_client
  - psutil
  - pyarrow=7
  - pynvml  # Only tested here
  - pytest
  - pytest-cov
  - pytest-faulthandler
  - pytest-repeat
  - pytest-rerunfailures
  - pytest-timeout
  - python-snappy >=0.5.3  # Only tested here
  - pytorch  # Only tested here
  - requests
  - s3fs
  - scikit-learn
  - scipy
  - sortedcollections
  - tblib
  - toolz
  - torchvision  # Only tested here
  - tornado >=6.2
  - zict
  - zstandard >=0.9.0
  - pip:
      - git+https://github.com/dask/dask
      - git+https://github.com/dask/crick  # Only tested here
      - keras
