name: dask-distributed
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - click=8.0
  - cloudpickle=1.5.0
  - cytoolz=0.10.1
  - jinja2=2.10.3
  - locket=1.0.0
  - msgpack-python=1.0.0
  - packaging=20.0
  - psutil=5.7.2
  - pyyaml=5.3.1
  - sortedcontainers=2.0.5
  - tblib=1.6.0
  - toolz=0.10.0
  - tornado=6.0.4
  - urllib3=1.24.3
  - zict=3.0.0
  # Distributed depends on the latest version of Dask
  - pip
  - pip:
    - git+https://github.com/dask/dask
  # test dependencies
  - pytest
  - pytest-cov
  - pytest-faulthandler
  - pytest-repeat
  - pytest-rerunfailures
  - pytest-timeout
