name: Test Report

on:
  schedule:
    # Run 2h after the daily tests.yaml
    - cron: "0 8,20 * * *"
  workflow_dispatch:

jobs:
  test-report:
    name: Test Report
    # Do not run the report job on forks
    if: github.repository == 'dask/distributed' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          condarc-file: continuous_integration/condarc
          use-mamba: true
          python-version: 3.9
          environment-file: continuous_integration/scripts/test-report-environment.yml
          activate-environment: dask-distributed

      - name: Show conda options
        shell: bash -l {0}
        run: conda config --show

      - name: mamba list
        shell: bash -l {0}
        run: mamba list

      - name: Generate report
        shell: bash -l {0}
        run: |
          python continuous_integration/scripts/test_report.py --max-days 90 --max-runs 50 --nfails 1 -o test_report.html
          python continuous_integration/scripts/test_report.py --max-days 7 --max-runs 50 --nfails 2 -o test_short_report.html --title "Test Short Report"
          mkdir deploy
          mv test_report.html test_short_report.html deploy/

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: deploy
